import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_FAMILY, FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";
import { MWREVIEWSSECBG, HEADINGIMG } from "@/values/Constants/ImageConstants";

export const MUIStyle = {
    ReviewSec: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: `url(${MWREVIEWSSECBG})`,
        backgroundSize: "cover",
        backgroundPosition: "center center",
        backgroundRepeat: "no-repeat",
        width: "100%",
        padding: {
            xs: "50px 0",
            sm: "50px 0",
            md: "86px 0 30px",
            lg: "86px 0 30px",
            xl: "86px 0 30px",
        },
    },

    Row: {
        display: "flex",
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row",
            lg: "row",
            xl: "row",
        },
        justifyContent: "space-between",
        alignItems: "flex-end",
        gap: {
            xs: "20px",
            sm: "20px",
            md: "90px",
            lg: "90px",
            xl: "90px",
        }
    },
    ReviewImage: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
        width: {
            xs: "100%",
            sm: "100%",
            md: "50%",
            lg: "50%",
            xl: "50%",
        },
        height: {
            xs: "300px",
            sm: "300px",
            md: "700px",
            lg: "700px",
            xl: "700px",
        },
        "& img": {
            width: "100%",
            height: "100%",
            objectFit: "cover",
            borderRadius: "20px",
        },
    },
    ReviewContent: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: {
            xs: "100%",
            sm: "100%",
            md: "50%",
            lg: "50%",
            xl: "50%",
        },
    },
    ReviewContentBox: {
        display: "flex",
        flexDirection: "column",
        justifyContent: {
            xs: "center",
            sm: "center",
            md: "flex-start",
            lg: "flex-start",
            xl: "Flex-start",
        },
        marginBottom: "64px",
        alignItems: {
            xs: "center",
            sm: "center",
            md: "flex-start",
            lg: "flex-start",
            xl: "Flex-start",
        },
        width: "100%",

    },
    ReviewTitle: {
        fontSize: {
            xs: FONT_SIZE.text22,
            sm: FONT_SIZE.text22,
            md: FONT_SIZE.text22,
            lg: FONT_SIZE.heading28,
            xl: FONT_SIZE.heading28,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.MGoldPrimary,
        marginBottom: "30px",
        lineHeight: "120%",
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
        },
    },
    ReviewDesc: {
        fontFamily: FONT_FAMILY,
        fontSize: {
            xs: FONT_SIZE.heading28,
            sm: FONT_SIZE.heading28,
            md: FONT_SIZE.heading28,
            lg: FONT_SIZE.heading40,
            xl: FONT_SIZE.heading40,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.white,
        lineHeight: "130%",
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
        },
    },
    ReviewOuter: {
        padding: {
            xs: "0px",
            sm: "0px",
            md: "0 20px",
            lg: "0 20px",
            xl: "0 20px",
        },
    },
    ReviewSlider: {
        position: "relative",
        width: "100%",
    },
    SliderArrowBtns: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "20px",
        marginTop: {
            xs: "20px",
            sm: "20px",
            md: "20px",
            lg: "0px",
            xl: "0px",
        },
        position: {
            xs: "initial",
            sm: "initial",
            md: "initial",
            lg: "absolute",
            xl: "absolute",
        },
        bottom: {
            xs: "5%",
            sm: "5%",
            md: "5%",
            lg: "10%",
            xl: "10%",
        },
        right: "5%",
        zIndex: "1",
    },
    SliderArrowBtn: {
        background: commonColor.Trans,
        color: '#0A774F',
        fontSize: FONT_SIZE.text20,
        fontWeight: FONT_WEIGHT.MEDIUM,
        border: "2px solid #0A774F",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "10px",
        borderRadius: "50%",
        transition: "all 0.3s ease",
        boxShadow: " 0 7px 24px rgba(206, 149, 45, 0)",
        "&:hover": {
            color: commonColor.MGoldPrimary,
            borderColor: `${commonColor.MGoldPrimary} !important`,
            boxShadow: " 0 7px 24px rgba(206, 149, 45, 0.42)",
        },
    },

    ReviewBox: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        padding: {
            xs: "20px",
            sm: "20px",
            md: "26px",
            lg: "26px",
            xl: "26px",
        },
        gap: "30px",
        background: commonColor.MWDarkGreen,
        borderRadius: "20px",
    },
    ReviewQuoteImg: {
        width: "30px",
        height: "30px",
        objectFit: "contain",
        marginBottom: "20px",
    },
    ReviewAreaDesc: {
        fontFamily: FONT_FAMILY,
        fontSize: {
            xs: FONT_SIZE.text16,
            sm: FONT_SIZE.text16,
            md: FONT_SIZE.text20,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.REGULAR,
        color: commonColor.white,
        lineHeight: "160%",
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
        },
    },
    ReviewUser: {
        display: "flex",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: "20px",
    },
    ReviewUserImg: {
        width: "60px",
        height: "60px",
        objectFit: "cover",
        borderRadius: "50%",
    },
    ReviewUserContent: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        gap: "5px",
    },
    ReviewUserName: {
        fontFamily: FONT_FAMILY,
        fontSize: [
            FONT_SIZE.text16,
            FONT_SIZE.text16,
            FONT_SIZE.text20,
            FONT_SIZE.heading24,
            FONT_SIZE.heading24,
        ],
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.white,
        lineHeight: "130%",
    },
    ReviewUserDesignation: {
        fontFamily: FONT_FAMILY,
        fontSize: FONT_SIZE.text16,
        fontWeight: FONT_WEIGHT.REGULAR,
        color: commonColor.MWLightGrey,
        lineHeight: "130%",
    },


};
