import Head from "next/head";
import Script from "next/script";

export const metadata = {
    title: "Luxe Interiors",
    description: "Generated by Websadroit",
};

export default function LuxeInteriorsLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {children}
                <Script src={process.env.BASE_URL + "/js/jquery-3.7.1.js"} type="text/javascript" />
                <Script src={process.env.BASE_URL + "/js/jquery.matchHeight.js"} type="text/javascript" />
            </body>
        </html>

    );
}