// import "./globals.css";
// import "./globals1.css"; // for Tallk styles
import Script from "next/script";
import "./globals2.css"; // for MentalWellness styles

export const metadata = {
  title: "Create Websadroit App",
  description: "Generated by Websadroit",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}
        <Script src={process.env.BASE_URL + "/js/jquery-3.7.1.js"} type="text/javascript" />
        <Script src={process.env.BASE_URL + "/js/mainScript.js"} type="text/javascript" />
      </body>
    </html>
  );
}
