import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_FAMILY, FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";
import { MWFACILITYSEC, HEADINGIMG } from "@/values/Constants/ImageConstants";

export const MUIStyle = {
    FacilitySec: {
        overflowX: "hidden",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: `url(${MWFACILITYSEC})`,
        backgroundSize: "cover",
        backgroundPosition: "center center",
        backgroundRepeat: "no-repeat",
        width: "100%",
        padding: {
            xs: "50px 0",
            sm: "50px 0",
            md: "86px 0",
            lg: "86px 0",
            xl: "86px 0",
        },
    },
    HeadingRow: {
        display: "flex",
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row",
            lg: "row",
            xl: "row",
        },
        justifyContent: "center",
        alignItems: "center",
        gap: {
            xs: "20px",
            sm: "20px",
            md: "30px",
            lg: "30px",
            xl: "30px",
        },
        marginBottom: {
            xs: "30px",
            sm: "30px",
            md: "64px",
            lg: "64px",
            xl: "64px",

        },
    },
    HeadingBox: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        textAlign: "center",
        gap: {
            xs: "10px",
            sm: "10px",
            md: "20px",
            lg: "20px",
            xl: "20px",
        },
        maxWidth: {
            xs: "100%",
            sm: "100%",
            md: "50%",
            lg: "45%",
            xl: "45%",
        },
    },
    FacilitySecTitle: {
        color: commonColor.MGoldPrimary,
        fontSize: {
            xs: FONT_SIZE.text22,
            sm: FONT_SIZE.text22,
            md: FONT_SIZE.text22,
            lg: FONT_SIZE.heading28,
            xl: FONT_SIZE.heading28,
        },
        fontWeight: FONT_WEIGHT.BOLD,
    },
    FacilitySecDesc: {
        color: commonColor.MSecondary,
        fontSize: {
            xs: FONT_SIZE.heading28,
            sm: FONT_SIZE.heading28,
            md: FONT_SIZE.heading28,
            lg: FONT_SIZE.heading36,
            xl: FONT_SIZE.heading36,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        position: "relative",
        "&:before": {
            content: "''",
            position: "absolute",
            width: "40px",
            height: "40px",
            background: `url(${HEADINGIMG})`,
            backgroundSize: "cover",
            backgroundPosition: "center center",
            backgroundRepeat: "no-repeat",
            top: "-10px",
            right: "-10px",
        },
    },
    FacilityRow: {
        display: "grid",
        gridTemplateColumns: {
            xs: "1fr",
            sm: "1fr",
            md: "1fr 1fr",
            lg: "1fr 1fr",
            xl: "1fr 1fr",
        },
        justifyContent: "space-between",
        alignItems: "center",
        gap: {
            xs: "20px",
            sm: "20px",
            md: "30px",
            lg: "30px",
            xl: "30px",
        },
    },
    FacilityBox: {
        display: "flex",
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row-reverse",
            lg: "row-reverse",
            xl: "row-reverse",
        },
        justifyContent: "Flex-start",
        alignItems: "stretch",
        background: commonColor.white,
        borderRadius: "20px",
        overflow: "hidden",
        position: "relative",
        minHeight: "480px",
        boxShadow: "0px 8px 20px rgba(0, 0, 0, 0.1)",
    },
    FacilityImgBox: {
        width: {
            xs: "100%",
            sm: "100%",
            md: "100%",
            lg: "40%",
            xl: "40%",
        },
        height: {
            xs: "33%",
            sm: "33%",
            md: "100%",
            lg: "100%",
            xl: "100%",
        },
        position: "absolute",
        top: "0",
        left: "0",

    },
    FacilityImg: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
    },
    FacilityContentBox: {
        width: {
            xs: "100%",
            sm: "100%",
            md: "100%",
            lg: "60%",
            xl: "60%",
        },
        padding: {
            xs: "260px 20px 20px 20px",
            sm: "260px 20px 20px 20px",
            md: "20px",
            lg: "20px",
            xl: "20px",
        },
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-start",
    },
    FacilityHeading: {
        color: commonColor.MGoldPrimary,
        fontSize: FONT_SIZE.text20,
        fontWeight: FONT_WEIGHT.MEDIUM,
        marginBottom: "10px",
    },
    FacilityTitle: {
        color: commonColor.MBlack,
        fontSize: {
            xs: FONT_SIZE.heading28,
            sm: FONT_SIZE.heading28,
            md: FONT_SIZE.heading28,
            lg: FONT_SIZE.heading32,
            xl: FONT_SIZE.heading32,
        },
        lineHeight: "120%",
        fontWeight: FONT_WEIGHT.MEDIUM,
        marginBottom: {
            xs: "10px",
            sm: "10px",
            md: "20px",
            lg: "25px",
            xl: "25px",
        },
    },
    FacilityDesc: {
        color: commonColor.MMediumGrey,
        fontSize: FONT_SIZE.text16,
        fontWeight: FONT_WEIGHT.REGULAR,
    },
    FacilityUlBox: {
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        listStyle: "none",
        padding: "20px 0",
        margin: "0",
        gap: "10px",
    },
    FacilityLi: {
        display: "flex",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: "10px",
    },
    FacilityIcon: {
        width: {
            xs: "17px",
            sm: "17px",
            md: "17px",
            lg: "20px",
            xl: "20px",
        },
        height: {
            xs: "17px",
            sm: "17px",
            md: "17px",
            lg: "20px",
            xl: "20px",
        },
        objectFit: "contain",
    },
    FacilityLiText: {
        color: "#493E2A",
        fontSize: [
            FONT_SIZE.text16,
            FONT_SIZE.text16,
            FONT_SIZE.text16,
            FONT_SIZE.text18,
            FONT_SIZE.text18,
        ],
        fontWeight: FONT_WEIGHT.MEDIUM,
    },
    FacilityBtn: {
        display: "flex",
        gap: "10px",
        alignItems: "center",
        justifyContent: "center",
        background: commonColor.Trans,
        color: commonColor.MGoldPrimary,
        fontSize: {
            xs: FONT_SIZE.text16,
            sm: FONT_SIZE.text16,
            md: FONT_SIZE.text16,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        boxShadow: "none !important",
        padding: "10px 20px 10px 0px",
        border: "none !important",
        "&:hover": {
            background: commonColor.Trans,
        },

    },
    FacilityBtnIcon: {
        width: {
            xs: "25px",
            sm: "25px",
            md: "25px",
            lg: "36px",
            xl: "36px",
        },
        height: "36px",
        objectFit: "contain",
    },


};
