import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_FAMILY, FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";
import { MWSERVICEBG, HEADINGIMG } from "@/values/Constants/ImageConstants";

export const MUIStyle = {
    ServiceSec: {
        overflowX: "hidden",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: `url(${MWSERVICEBG})`,
        backgroundSize: "cover",
        backgroundPosition: "center center",
        backgroundRepeat: "no-repeat",
        width: "100%",
        padding: {
            xs: "50px 0",
            sm: "50px 0",
            md: "86px 0 30px",
            lg: "86px 0 30px",
            xl: "86px 0 30px",
        },
    },
    HeadingRow: {
        display: "flex",
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row",
            lg: "row",
            xl: "row",
        },
        justifyContent: "center",
        alignItems: "center",
        gap: {
            xs: "20px",
            sm: "20px",
            md: "30px",
            lg: "30px",
            xl: "30px",
        },
        marginBottom: {
            xs: "30px",
            sm: "30px",
            md: "48px",
            lg: "48px",
            xl: "48px",

        },
    },
    HeadingBox: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        textAlign: "center",
        gap: {
            xs: "10px",
            sm: "10px",
            md: "20px",
            lg: "20px",
            xl: "20px",
        },
        maxWidth: {
            xs: "100%",
            sm: "100%",
            md: "50%",
            lg: "45%",
            xl: "45%",
        },
    },
    ServiceSecTitle: {
        color: commonColor.MGoldPrimary,
        fontSize: {
            xs: FONT_SIZE.text22,
            sm: FONT_SIZE.text22,
            md: FONT_SIZE.text22,
            lg: FONT_SIZE.heading28,
            xl: FONT_SIZE.heading28,
        },
        fontWeight: FONT_WEIGHT.BOLD,
    },
    ServiceSecDesc: {
        color: commonColor.white,
        fontSize: {
            xs: FONT_SIZE.heading28,
            sm: FONT_SIZE.heading28,
            md: FONT_SIZE.heading28,
            lg: FONT_SIZE.heading40,
            xl: FONT_SIZE.heading40,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        position: "relative",
        "&:before": {
            content: "''",
            position: "absolute",
            width: "40px",
            height: "40px",
            background: `url(${HEADINGIMG})`,
            backgroundSize: "cover",
            backgroundPosition: "center center",
            backgroundRepeat: "no-repeat",
            top: "-10px",
            right: "-10px",
        },
    },
    ServiceOuter: {
        padding: {
            xs: "0 10px",
            sm: "0 10px",
            md: "0 10px",
            lg: "0 10px",
            xl: "0 10px",
        },
    },
    ServiceSlider: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "Flex-start",
        alignItems: "Flex-start",
        borderRadius: "20px",
        overflow: "hidden",
    },
    ServiceImage: {
        width: "100%",
        height: {
            xs: "auto",
            sm: "auto",
            md: "290px",
            lg: "290px",
            xl: "290px",
        },
        position: "relative",

    },
    ServiceImg: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
    },
    ServiceIcon: {
        position: "absolute",
        bottom: "0px",
        left: "20px",
        height: "76px",
        width: "86px",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: "10px 10px 0px 0",
        background: commonColor.MWGreenDeep,
        "& img": {
            width: "50px",
            height: "50px",
            objectFit: "contain",
        },
    },
    ServiceContent: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: {
            xs: "20px",
            sm: "20px",
            md: "30px",
            lg: "30px",
            xl: "30px",
        },
        padding: {
            xs: "20px",
            sm: "20px",
            md: "30px",
            lg: "30px",
            xl: "30px",
        },
        background: commonColor.MWDarkGreen,
        borderRadius: "0px 0px 10px 10px",
        width: "100%",
        minHeight: {
            xs: "auto",
            sm: "auto",
            md: "280px",
            lg: "280px",
            xl: "280px",
        },
    },
    ServiceTitle: {
        color: commonColor.white,
        fontSize: FONT_SIZE.heading24,
        fontWeight: FONT_WEIGHT.BOLD,
        marginBottom: "10px",
    },
    ServiceDesc: {
        color: commonColor.MLightGreenText,
        fontSize: FONT_SIZE.text18,
        fontWeight: FONT_WEIGHT.REGULAR,
    },
    ServiceBtn: {
        background: commonColor.Trans,
        color: commonColor.white,
        fontSize: {
            xs: FONT_SIZE.text16,
            sm: FONT_SIZE.text16,
            md: FONT_SIZE.text20,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "10px",
        boxShadow: "none !important",
        padding: "10px 20px",
        borderRadius: "30px",
        lineHeight: "150%",
        borderColor: `${commonColor.white} !important`,
        "&:hover": {
            background: commonColor.Trans,
            color: commonColor.MGoldPrimary,
            borderColor: `${commonColor.MGoldPrimary} !important`,
            boxShadow: " 0 7px 24px rgba(206, 149, 45, 0.42) !important",
        },
    },
    SliderRow: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: "20px",
        marginTop: "64px",
    },
    SliderArrowBtns: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "20px",
    },
    SliderArrowBtn: {
        background: commonColor.Trans,
        color: '#0A774F',
        fontSize: FONT_SIZE.text20,
        fontWeight: FONT_WEIGHT.MEDIUM,
        border: "2px solid #0A774F",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "10px",
        borderRadius: "50%",
        transition: "all 0.3s ease",
        boxShadow: " 0 7px 24px rgba(206, 149, 45, 0)",
        "&:hover": {
            color: commonColor.MGoldPrimary,
            borderColor: `${commonColor.MGoldPrimary} !important`,
            boxShadow: " 0 7px 24px rgba(206, 149, 45, 0.42)",
        },
    },

    ViewBtn: {
        background: commonColor.MWDarkGreen,
        color: commonColor.MWhiteBg,
        fontSize: {
            xs: FONT_SIZE.text22,
            sm: FONT_SIZE.text22,
            md: FONT_SIZE.heading24,
            lg: FONT_SIZE.heading24,
            xl: FONT_SIZE.heading24,
        },
        border: `2px solid ${commonColor.MWDarkGreen}`,
        fontWeight: FONT_WEIGHT.MEDIUM,
        boxShadow: " 0 7px 24px rgba(206, 149, 45, 0)",
        padding: "10px 25px",
        borderRadius: "30px",
        lineHeight: "130%",
        "&:hover": {
            background: commonColor.Trans,
            color: commonColor.MGoldPrimary,
            borderColor: commonColor.MGoldPrimary,
            boxShadow: " 0 7px 24px rgba(206, 149, 45, 0.42)",
        },
    },


};
