import { commonColor } from "../Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "../Constants/FontConstants";

export const commonStyle = {
    TitleBox: {
        padding: "10px 32px",
        borderRadius: "10px",
        background: "linear-gradient(91.02deg, rgb(49 102 255 / 15%) 0%, rgb(219 32 160 / 15%) 100%)",
    },
    Title: {
        fontSize: FONT_SIZE.text20,
        fontWeight: FONT_WEIGHT.BOLD,
    },
    CustomBtnBox: {
        padding: "6px",
        background: "linear-gradient(91.02deg, rgb(49 102 255 / 45%) 0%, rgb(219 32 160 / 45%) 100%)",
        borderRadius: "12px",
    },
    CustomBtn: {
        background: "linear-gradient(91.02deg, #3166FF 0%, #DB20A0 100%)",
        color: commonColor.white,
        fontSize: FONT_SIZE.text16,
        fontWeight: FONT_WEIGHT.BOLD,
        padding: "10px 32px",
        borderRadius: "10px",
        fontSize: FONT_SIZE.text20,
        boxShadow: "none",
    },
    HTCCustomBtnBox: {
        padding: "5px",
        background: commonColor.HCTGreen,
        borderRadius: "50px",
    },
    HCTCustomBtn: {
        background: commonColor.HCTGreen,
        color: commonColor.white,
        fontSize: {
            xs: FONT_SIZE.text16,
            sm: FONT_SIZE.text16,
            md: FONT_SIZE.text16,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.BOLD,
        padding: "7px 32px",
        borderRadius: "50px",
        fontSize: FONT_SIZE.text20,
        boxShadow: "none",
        border: "1px solid",
        borderColor: commonColor.white,
    },
    CustomBtnBox1: {
        padding: "2px",
        background: "linear-gradient(91.02deg, rgb(49 102 255 / 45%) 0%, rgb(219 32 160 / 45%) 100%)",
        borderRadius: "12px",
    },
    CustomBtn1: {
        background: "linear-gradient(91.02deg, #3166FF 0%, #DB20A0 100%)",
        color: commonColor.white,
        fontSize: FONT_SIZE.text16,
        fontWeight: FONT_WEIGHT.BOLD,
        padding: "10px 32px",
        borderRadius: "10px",
        fontSize: FONT_SIZE.text20,
        boxShadow: "none",
    },
    CustomTallkBtn: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "10px",
        background: commonColor.btnGradient,
        color: commonColor.white,
        fontSize: FONT_SIZE.text18,
        fontWeight: FONT_WEIGHT.BOLD,
        lineHeight: "150%",
        padding: "15px 32px",
        borderRadius: "10px",
        boxShadow: "none !important",
        transition: "all 0.3s ease-in-out",
        "&:hover": {
            background: commonColor.btnGradient,
            scale: "1.03",
        },
    },
    HTCBtn: {
        background: commonColor.Trans,
        color: commonColor.HCTGreen,
        borderRadius: "50px",
        padding: {
            xs: "15px 30px",
            sm: "15px 30px",
            md: "20px 35px",
            lg: "20px 35px",
            xl: "20px 35px",
        },
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "10px",
        minHeight: {
            xs: "40px",
            sm: "40px",
            md: "50px",
            lg: "50px",
            xl: "50px",
        },
        fontSize: {
            xs: FONT_SIZE.text18,
            sm: FONT_SIZE.text18,
            md: FONT_SIZE.text18,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.BOLD,
        boxShadow: "none",
        lineHeight: "24px",
        border: `2px solid ${commonColor.HCTGreen}`,
        "&:hover": {
            background: commonColor.white,
            boxShadow: "none",
        },
    },
    HTCBtnIcon: {
        width: "30px",
        height: "30px",
        objectFit: "contain",
    },
};